[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
replicator = { path = "../replicator", features = ["utils"] }
tracing-subscriber = "0.3.18"
async-std = "1.12.0"
hypercore = { path  = "../../hypercore", default_features = false, features = ["tokio"]}
hypercore-protocol = { path  = "../../hypercore-protocol-rs", features = ["debug", "tokio"], default_features = false }
random-access-memory = "3.0.0"
tokio = { version = "1.37.0", features = ["sync"] }
