[package]
name = "replicator"
version = "0.1.0"
edition = "2021"

[features]
utils = []

[dependencies]
async-std = "1.12.0"
futures-lite = "2.3.0"
hypercore = { git = "https://github.com/cowlicks/hypercore.git", branch = "add-events" }
hypercore-protocol =  { git  = "https://github.com/cowlicks/hypercore-protocol-rs.git", branch = "add-events" }
random-access-storage = "5.0.0"
tracing = "0.1.40"
thiserror = "1.0.50"
tokio = { version = "1.37.0", features = ["sync", "time"] }
async-channel = "1"
async-trait = "0.1.81"

[dev-dependencies]
rusty_nodejs_repl = { path = "../../rsjs" }
async-process = "2.2.1"
async-std = "1.12.0"
hex = "0.4.3"
piper = "0.2.1"
serde_json = "1.0.116"
tempfile = "3.10.1"
tokio = {version = "1.37.0", features = ["rt", "macros", "sync"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
utils = { path = "../utils" }
macros = { path = "../macros" }
random-access-memory = "3.0.0"
