[package]
name = "replicator"
version = "0.1.0"
edition = "2021"

[features]
utils = []

[dependencies]
async-std = "1.12.0"
futures-lite = "2.3.0"
hypercore = { path  = "../../core", default_features = false, features = ["tokio"]}
hypercore-protocol = { path  = "../../protocol", features = ["debug", "tokio"], default_features = false }
random-access-storage = "5.0.0"
tracing = "0.1.40"
thiserror = "1.0.50"
tokio = { version = "1.37.0", features = ["sync"] }

[dev-dependencies]
async-process = "2.2.1"
async-std = "1.12.0"
hex = "0.4.3"
piper = "0.2.1"
serde_json = "1.0.116"
tempfile = "3.10.1"
tokio = {version = "1.37.0", features = ["rt", "macros", "sync"] }
tracing-subscriber = "0.3.18"
utils = { path = "../utils" }
macros = { path = "../macros" }
random-access-memory = "3.0.0"
